// Token generation system. `src/tokens.ts` is the single source of truth; this script
// emits platform-specific token files from it so native apps stay in sync with the
// web/RN design system. Run with `npm run generate:tokens -w @companion/design-system`
// (or `make tokens`). Add new targets by writing another `emit*` function + output path.
//
// Targets:
//   - Swift  -> apps/visionos/Sources/Tokens.swift  (SwiftUI: Brand.* colors, spacing,
//               radius, type scale, shadows)
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { writeFileSync } from "node:fs";
import { colors, space, radius, font, shadow, control, layout } from "../src/tokens.ts";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");

const HEADER = (source: string) =>
  `// GENERATED by packages/design-system/scripts/generate-tokens.ts — do not edit.\n` +
  `// Source of truth: ${source}\n`;

// "#f76808" -> "0xF76808"; a Swift color literal expects a hex int.
const hex = (value: string) => `0x${value.replace("#", "").toUpperCase()}`;

// Swift identifiers can't start with a digit: "2xl" -> "xl2", "3xl" -> "xl3".
const swiftKey = (key: string) =>
  /^\d/.test(key) ? key.replace(/^(\d+)(.*)$/, (_m, d, rest) => `${rest}${d}`) : key;

const weightToSwift: Record<string, string> = {
  "400": ".regular",
  "500": ".medium",
  "600": ".semibold",
  "700": ".bold",
};

// First concrete family from a CSS font stack: 'Geist, ui-sans-serif, …' -> "Geist".
const firstFamily = (stack: string) =>
  stack.split(",")[0].trim().replace(/^["']|["']$/g, "");

function emitSwift(): string {
  const line = (indent: number, s: string) => `${" ".repeat(indent)}${s}`;
  const out: string[] = [];
  out.push(HEADER("packages/design-system/src/tokens.ts"));
  out.push("import SwiftUI");
  out.push("");
  out.push("/// Companion brand design tokens, generated from the shared design system.");
  out.push("enum Brand {");

  // Colors (flat on Brand for the common case, e.g. `Brand.accent`).
  out.push(line(4, "// MARK: Colors"));
  for (const [key, value] of Object.entries(colors)) {
    out.push(line(4, `static let ${key} = Color(hex: ${hex(value as string)})`));
  }
  out.push("");

  // Spacing
  out.push(line(4, "enum Space {"));
  for (const [key, value] of Object.entries(space)) {
    out.push(line(8, `static let ${swiftKey(key)}: CGFloat = ${value}`));
  }
  out.push(line(4, "}"));
  out.push("");

  // Radius
  out.push(line(4, "enum Radius {"));
  for (const [key, value] of Object.entries(radius)) {
    out.push(line(8, `static let ${swiftKey(key)}: CGFloat = ${value}`));
  }
  out.push(line(4, "}"));
  out.push("");

  // Type scale
  out.push(line(4, "enum FontSize {"));
  for (const [key, value] of Object.entries(font.size)) {
    out.push(line(8, `static let ${swiftKey(key)}: CGFloat = ${value}`));
  }
  out.push(line(4, "}"));
  out.push("");

  out.push(line(4, "enum FontWeight {"));
  for (const [key, value] of Object.entries(font.weight)) {
    out.push(line(8, `static let ${key}: Font.Weight = ${weightToSwift[value as string] ?? ".regular"}`));
  }
  out.push(line(4, "}"));
  out.push("");

  out.push(line(4, `static let sansFamily = ${JSON.stringify(firstFamily(font.sans))}`));
  out.push(line(4, `static let monoFamily = ${JSON.stringify(firstFamily(font.mono))}`));
  out.push("");

  // Control heights + layout metrics
  out.push(line(4, "enum Metric {"));
  for (const [key, value] of Object.entries(control)) {
    out.push(line(8, `static let control${key.charAt(0).toUpperCase()}${key.slice(1)}: CGFloat = ${value}`));
  }
  for (const [key, value] of Object.entries(layout)) {
    out.push(line(8, `static let ${key}: CGFloat = ${value}`));
  }
  out.push(line(4, "}"));
  out.push("");

  // Shadows
  out.push(line(4, "enum Shadow {"));
  for (const [key, s] of Object.entries(shadow)) {
    const sh = s as { shadowColor: string; shadowOffset: { width: number; height: number }; shadowOpacity: number; shadowRadius: number };
    out.push(line(8, `static let ${key} = ShadowToken(color: Color(hex: ${hex(sh.shadowColor)}), opacity: ${sh.shadowOpacity}, radius: ${sh.shadowRadius}, x: ${sh.shadowOffset.width}, y: ${sh.shadowOffset.height})`));
  }
  out.push(line(4, "}"));

  out.push("}");
  out.push("");
  out.push("/// A design-system shadow, matching the RN shadow props on the web/mobile side.");
  out.push("struct ShadowToken {");
  out.push("    let color: Color");
  out.push("    let opacity: Double");
  out.push("    let radius: CGFloat");
  out.push("    let x: CGFloat");
  out.push("    let y: CGFloat");
  out.push("}");
  out.push("");
  out.push("extension View {");
  out.push("    /// Applies a brand shadow token.");
  out.push("    func brandShadow(_ token: ShadowToken) -> some View {");
  out.push("        shadow(color: token.color.opacity(token.opacity), radius: token.radius, x: token.x, y: token.y)");
  out.push("    }");
  out.push("}");
  out.push("");
  out.push("extension Color {");
  out.push("    /// 24-bit RGB (`0xRRGGBB`), opaque. Used by generated brand color tokens.");
  out.push("    init(hex: UInt32) {");
  out.push("        self.init(");
  out.push("            .sRGB,");
  out.push("            red: Double((hex >> 16) & 0xFF) / 255,");
  out.push("            green: Double((hex >> 8) & 0xFF) / 255,");
  out.push("            blue: Double(hex & 0xFF) / 255,");
  out.push("            opacity: 1");
  out.push("        )");
  out.push("    }");
  out.push("}");
  out.push("");
  return out.join("\n");
}

const swiftPath = resolve(repoRoot, "apps/visionos/Sources/Tokens.swift");
writeFileSync(swiftPath, emitSwift());
console.log(`wrote ${swiftPath}`);
