import SwiftUI
import WebKit

/// Snapshot of the formatting-toolbar state posted by the editor on each selection change.
/// Mirrors the web/RN `FormatState` (active + enabled per command).
struct FormatState: Equatable {
    var hasSelection = false
    var active: Set<String> = []
    var enabled: Set<String> = []
    /// Whether the editor has reported a state yet (before that, treat everything enabled).
    var received = false

    func isActive(_ name: String) -> Bool { active.contains(name) }
    func isEnabled(_ name: String) -> Bool { !received || enabled.contains(name) }
}

/// Host-side data access the editor needs for references + embeds. Each returns raw JSON
/// (from the core) that gets injected straight back into the WebView.
struct EditorBridge {
    var search: (_ query: String, _ type: String) -> String
    var lookup: (_ id: String) -> String
    var documentDataURL: (_ id: String) -> String
}

/// JSON-encodes a Swift string into a JS string literal (quotes included), escaping `<`
/// so it can't break out of a `<script>` tag.
func jsStringLiteral(_ s: String) -> String {
    guard
        let data = try? JSONSerialization.data(withJSONObject: [s]),
        let json = String(data: data, encoding: .utf8)
    else { return "\"\"" }
    return String(json.dropFirst().dropLast()).replacingOccurrences(of: "<", with: "\\u003c")
}

/// Drives the editor from outside (toolbar + native pickers). Holds a weak reference to the
/// hosted `WKWebView` and injects the same `window.__*` globals the RN host uses.
@MainActor final class EditorController {
    weak var webView: WKWebView?

    private func run(_ js: String) { webView?.evaluateJavaScript(js) }

    func format(_ name: String) { run("window.__format && window.__format('\(name)');") }
    func insertTable() { run("window.__insertTable && window.__insertTable();") }
    /// Insert a `[[` trigger at the cursor, opening the editor's inline autocomplete popup.
    func insertReference() { run("window.__insertReference && window.__insertReference();") }
    func insertDocumentEmbed(id: String, filename: String) {
        run("window.__insertDocumentEmbed && window.__insertDocumentEmbed(\(jsStringLiteral(id)), \(jsStringLiteral(filename)));")
    }
    func resolveLink(_ requestId: Int, _ json: String) { run("window.__resolveLink && window.__resolveLink(\(requestId), \(json));") }
    func resolveDoc(_ requestId: Int, _ json: String) { run("window.__resolveDoc && window.__resolveDoc(\(requestId), \(json));") }
    /// Run the picked table cell action, or tell the editor the menu was dismissed.
    func runTableAction(_ id: String) { run("window.__runTableAction && window.__runTableAction(\(jsStringLiteral(id)));") }
    func dismissTableMenu() { run("window.__dismissTableMenu && window.__dismissTableMenu();") }
}

/// A table cell menu request forwarded from the editor to be presented natively. `anchor`
/// is in WebView (CSS-pixel ≈ point) coordinates relative to the editor.
struct TableMenuModel {
    let items: [TableMenuItem]
    let anchor: CGPoint
}

/// One row of the table cell menu (mirrors the editor's `TableMenuItem`): an action, a
/// separator, or a submenu (`children`).
struct TableMenuItem: Decodable {
    let id: String?
    let label: String?
    let separator: Bool?
    let checked: Bool?
    let enabled: Bool?
    let children: [TableMenuItem]?
}

/// Hosts the shared ProseMirror editor (bundled from `@companion/editor` into
/// apps/visionos/Resources/editor.{js,css}, generated by `make visionos-editor`) inside a
/// `WKWebView`. The visionOS analogue of `Editor.tsx`'s react-native-webview host: same
/// offline bundle + postMessage bridge, different shell. Link autocomplete, pasted-UUID
/// lookup, and document embeds run over the bridge against the Go core. The editor owns its
/// content after seeding — recreate the view (`.id(date)`) to load a different note.
struct ProseMirrorEditor: UIViewRepresentable {
    let markdown: String
    let controller: EditorController
    let bridge: EditorBridge
    /// "full" is the document editor (headings/lists/marks + toolbar); "simple" is the
    /// plain-text-plus-references field used by quick capture.
    var variant: String = "full"
    var placeholder: String = ""
    var onChange: (String) -> Void
    var onFocusChange: (Bool) -> Void = { _ in }
    var onFormatState: (FormatState) -> Void = { _ in }
    var onTableMenu: (TableMenuModel) -> Void = { _ in }

    func makeCoordinator() -> Coordinator { Coordinator(self) }

    func makeUIView(context: Context) -> WKWebView {
        let ucc = WKUserContentController()
        ucc.add(context.coordinator, name: "editor")
        // The bundle posts via `window.ReactNativeWebView.postMessage` (its RN contract);
        // shim it onto the WKWebView message handler, before the bundle runs.
        ucc.addUserScript(WKUserScript(
            source: "window.ReactNativeWebView={postMessage:function(m){window.webkit.messageHandlers.editor.postMessage(m);}};",
            injectionTime: .atDocumentStart,
            forMainFrameOnly: true
        ))

        let config = WKWebViewConfiguration()
        config.userContentController = ucc

        let web = WKWebView(frame: .zero, configuration: config)
        web.isOpaque = false
        web.backgroundColor = .clear
        web.scrollView.backgroundColor = .clear
        web.scrollView.bounces = false
        controller.webView = web
        web.loadHTMLString(Coordinator.html(markdown: markdown, variant: variant, placeholder: placeholder), baseURL: nil)
        return web
    }

    func updateUIView(_ web: WKWebView, context: Context) {
        context.coordinator.parent = self   // keep closures fresh
    }

    static func dismantleUIView(_ web: WKWebView, coordinator: Coordinator) {
        web.configuration.userContentController.removeScriptMessageHandler(forName: "editor")
    }

    final class Coordinator: NSObject, WKScriptMessageHandler {
        var parent: ProseMirrorEditor
        init(_ parent: ProseMirrorEditor) { self.parent = parent }

        func userContentController(_ ucc: WKUserContentController, didReceive message: WKScriptMessage) {
            guard
                let body = message.body as? String,
                let data = body.data(using: .utf8),
                let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                let type = obj["type"] as? String
            else { return }
            let payload = obj["payload"]
            switch type {
            case "change":
                if let md = payload as? String { parent.onChange(md) }
            case "focus":
                parent.onFocusChange((payload as? Bool) ?? false)
            case "format":
                if let p = payload as? [String: Any] { parent.onFormatState(Self.parseFormat(p)) }
            case "linkSearch":
                if let p = payload as? [String: Any], let rid = Self.requestId(p) {
                    let json = parent.bridge.search(p["query"] as? String ?? "", p["type"] as? String ?? "all")
                    parent.controller.resolveLink(rid, json)
                }
            case "linkLookup":
                if let p = payload as? [String: Any], let rid = Self.requestId(p) {
                    let json = parent.bridge.lookup(p["id"] as? String ?? "")
                    parent.controller.resolveLink(rid, json)
                }
            case "docResolve":
                if let p = payload as? [String: Any], let rid = Self.requestId(p) {
                    let json = parent.bridge.documentDataURL(p["id"] as? String ?? "")
                    parent.controller.resolveDoc(rid, json)
                }
            case "tableMenu":
                if let model = Self.parseTableMenu(payload) { parent.onTableMenu(model) }
            default:
                break
            }
        }

        private static func parseTableMenu(_ payload: Any?) -> TableMenuModel? {
            guard
                let p = payload as? [String: Any],
                let itemsRaw = p["items"],
                let data = try? JSONSerialization.data(withJSONObject: itemsRaw),
                let items = try? JSONDecoder().decode([TableMenuItem].self, from: data)
            else { return nil }
            let anchor = p["anchor"] as? [String: Any] ?? [:]
            let x = (anchor["x"] as? Double) ?? Double(anchor["x"] as? Int ?? 0)
            let y = (anchor["y"] as? Double) ?? Double(anchor["y"] as? Int ?? 0)
            return TableMenuModel(items: items, anchor: CGPoint(x: x, y: y))
        }

        private static func requestId(_ p: [String: Any]) -> Int? {
            if let i = p["requestId"] as? Int { return i }
            if let d = p["requestId"] as? Double { return Int(d) }
            return nil
        }

        private static func parseFormat(_ p: [String: Any]) -> FormatState {
            var state = FormatState()
            state.received = true
            state.hasSelection = (p["hasSelection"] as? Bool) ?? false
            if let active = p["active"] as? [String: Any] {
                state.active = Set(active.compactMap { ($0.value as? Bool) == true ? $0.key : nil })
            }
            if let enabled = p["enabled"] as? [String: Any] {
                state.enabled = Set(enabled.compactMap { ($0.value as? Bool) == true ? $0.key : nil })
            }
            return state
        }

        /// Builds the WebView HTML: editor CSS + seeded globals + the bundle, matching
        /// `Editor.tsx`'s `buildHtml`. The simple variant is a transparent inline field; the
        /// full variant is a white document page.
        static func html(markdown: String, variant: String, placeholder: String) -> String {
            let css = resource("editor", "css")
            let js = resource("editor", "js")
            let initial = jsStringLiteral(markdown)
            let simple = variant == "simple"
            let bodyBg = simple ? "background:transparent;" : "min-height:100%;background:#ffffff;"
            let mountClass = simple ? "pm-compact" : "pm-wrap"
            return """
            <!DOCTYPE html>
            <html>
            <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
            <style>html,body{margin:0;padding:0;\(bodyBg)}\(css)</style>
            </head>
            <body>
            <div id="editor" class="\(mountClass)"></div>
            <script>window.__INITIAL_MARKDOWN__ = \(initial); window.__HAS_LINK_SOURCE__ = true; window.__INLINE_AUTOCOMPLETE__ = true; window.__HAS_DOCUMENT_SOURCE__ = true; window.__EDITOR_VARIANT__ = "\(variant)"; window.__PLACEHOLDER__ = \(jsStringLiteral(placeholder)); window.__SUBMIT_ON_ENTER__ = false; window.__DEBOUNCE_MS__ = undefined;</script>
            <script>\(js)</script>
            </body>
            </html>
            """
        }

        private static func resource(_ name: String, _ ext: String) -> String {
            guard
                let url = Bundle.main.url(forResource: name, withExtension: ext),
                let contents = try? String(contentsOf: url, encoding: .utf8)
            else { return "" }
            return contents
        }
    }
}
