// GENERATED by packages/design-system/scripts/generate-tokens.ts — do not edit.
// Source of truth: packages/design-system/src/tokens.ts

import SwiftUI

/// Companion brand design tokens, generated from the shared design system.
enum Brand {
    // MARK: Colors
    static let gray0 = Color(hex: 0xFFFFFF)
    static let gray25 = Color(hex: 0xFAFAF9)
    static let gray50 = Color(hex: 0xF5F5F3)
    static let gray100 = Color(hex: 0xEDEDEA)
    static let gray200 = Color(hex: 0xE0E0DC)
    static let gray300 = Color(hex: 0xCECECA)
    static let gray400 = Color(hex: 0xA7A7A1)
    static let gray500 = Color(hex: 0x7B7B75)
    static let gray600 = Color(hex: 0x595954)
    static let gray700 = Color(hex: 0x3E3E3A)
    static let gray800 = Color(hex: 0x2A2A27)
    static let gray900 = Color(hex: 0x1A1A18)
    static let gray950 = Color(hex: 0x111110)
    static let orange50 = Color(hex: 0xFFF4ED)
    static let orange100 = Color(hex: 0xFFE5D4)
    static let orange200 = Color(hex: 0xFECCAB)
    static let orange500 = Color(hex: 0xF76808)
    static let orange600 = Color(hex: 0xE04E02)
    static let orange700 = Color(hex: 0xB83A05)
    static let textPrimary = Color(hex: 0x1A1A18)
    static let textSecondary = Color(hex: 0x595954)
    static let textTertiary = Color(hex: 0x7B7B75)
    static let textDisabled = Color(hex: 0xA7A7A1)
    static let textInverse = Color(hex: 0xFFFFFF)
    static let textAccent = Color(hex: 0xE04E02)
    static let surfaceApp = Color(hex: 0xF5F5F3)
    static let surfaceCard = Color(hex: 0xFFFFFF)
    static let surfaceSunken = Color(hex: 0xEDEDEA)
    static let surfaceHover = Color(hex: 0xEDEDEA)
    static let surfaceActive = Color(hex: 0xE0E0DC)
    static let borderSubtle = Color(hex: 0xE0E0DC)
    static let borderDefault = Color(hex: 0xCECECA)
    static let borderStrong = Color(hex: 0xA7A7A1)
    static let borderFocus = Color(hex: 0xF76808)
    static let accent = Color(hex: 0xF76808)
    static let accentHover = Color(hex: 0xE04E02)
    static let accentActive = Color(hex: 0xB83A05)
    static let accentSoft = Color(hex: 0xFFF4ED)
    static let accentSoftBorder = Color(hex: 0xFECCAB)
    static let onAccent = Color(hex: 0xFFFFFF)
    static let success = Color(hex: 0x2E9E5B)
    static let warning = Color(hex: 0xD68A0C)
    static let danger = Color(hex: 0xD64545)
    static let dangerSoft = Color(hex: 0xFBECEC)
    static let info = Color(hex: 0x3B74D6)
    static let infoSoft = Color(hex: 0xEAF1FB)
    static let infoActive = Color(hex: 0x2B579E)

    enum Space {
        static let xs: CGFloat = 4
        static let sm: CGFloat = 6
        static let md: CGFloat = 8
        static let lg: CGFloat = 12
        static let xl: CGFloat = 16
        static let xxl: CGFloat = 24
        static let xxxl: CGFloat = 32
    }

    enum Radius {
        static let xs: CGFloat = 4
        static let sm: CGFloat = 6
        static let md: CGFloat = 8
        static let lg: CGFloat = 12
        static let xl: CGFloat = 16
        static let xxl: CGFloat = 20
        static let full: CGFloat = 999
    }

    enum FontSize {
        static let xs2: CGFloat = 11
        static let xs: CGFloat = 12
        static let sm: CGFloat = 13
        static let base: CGFloat = 14
        static let md: CGFloat = 15
        static let lg: CGFloat = 17
        static let xl: CGFloat = 20
        static let xl2: CGFloat = 24
        static let xl3: CGFloat = 30
    }

    enum FontWeight {
        static let regular: Font.Weight = .regular
        static let medium: Font.Weight = .medium
        static let semibold: Font.Weight = .semibold
        static let bold: Font.Weight = .bold
    }

    static let sansFamily = "Geist"
    static let monoFamily = "Geist Mono"

    enum Metric {
        static let controlSm: CGFloat = 28
        static let controlMd: CGFloat = 34
        static let controlLg: CGFloat = 40
        static let railW: CGFloat = 56
        static let railOpenW: CGFloat = 232
        static let listW: CGFloat = 300
        static let titlebarH: CGFloat = 44
        static let toolbarH: CGFloat = 52
        static let contentMax: CGFloat = 760
    }

    enum Shadow {
        static let sm = ShadowToken(color: Color(hex: 0x111110), opacity: 0.08, radius: 3, x: 0, y: 1)
        static let md = ShadowToken(color: Color(hex: 0x111110), opacity: 0.1, radius: 12, x: 0, y: 4)
        static let lg = ShadowToken(color: Color(hex: 0x111110), opacity: 0.14, radius: 28, x: 0, y: 12)
    }
}

/// A design-system shadow, matching the RN shadow props on the web/mobile side.
struct ShadowToken {
    let color: Color
    let opacity: Double
    let radius: CGFloat
    let x: CGFloat
    let y: CGFloat
}

extension View {
    /// Applies a brand shadow token.
    func brandShadow(_ token: ShadowToken) -> some View {
        shadow(color: token.color.opacity(token.opacity), radius: token.radius, x: token.x, y: token.y)
    }
}

extension Color {
    /// 24-bit RGB (`0xRRGGBB`), opaque. Used by generated brand color tokens.
    init(hex: UInt32) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: 1
        )
    }
}
